server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/petHome?useUnicode=true&characterEncoding=UTF-8&useSSL=false
mybatis:
  configuration: # 添加一个log打印mybatis执行的所有sql语句的配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true #开启实体类的驼峰转换
